version: '3.1'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: studio
      POSTGRES_PASSWORD: example
    ports:
      - 8282:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8181:8080
